import transcription from '../public/img/icons/transcript.svg';
import translation from '../public/img/icons/translation.svg';
import dubbing from '../public/img/icons/dubbing.svg';
import videoedit from '../public/img/icons/video-edit.svg';
import creator from '../public/img/icons/creator.svg';

export const LANGUAGES = [
  'English',
  'French',
  'German',
  'Spanish',
  'Swedish',
  'Portuguese',
  'Arabic',
  'Russian',
  'Chinese',
];

export const DASHBOARD_NAVLINKS = [
  {
    text: 'Pending',
    image: transcription,
    route: '/pending',
  },
  {
    text: 'Overlay Flags',
    image: videoedit,
    route: '/overlay-flags',
  },
  {
    text: 'Moderation',
    image: creator,
    route: '/moderation',
  },
];

export const SupportedLanguages = [
  {
    languageName: 'English (US)',
    localDialect: 'English',
    code: 'EN-US',
    translateCode: 'EN-US',
    countryCode: 'US',
    countryName: 'United States',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'Spanish',
    localDialect: 'Español',
    countryName: 'Spain',
    countryCode: 'ES',
    code: 'ES',
    translateCode: 'ES',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'Spanish (LATAM)',
    localDialect: 'Español',
    countryName: 'Mexico',
    countryCode: 'MX',
    code: 'ES',
    translateCode: 'ES',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'French',
    localDialect: 'Français',
    countryName: 'France',
    countryCode: 'FR',
    code: 'FR',
    translateCode: 'FR',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'French (QB)',
    localDialect: 'Français',
    countryName: 'Canada',
    countryCode: 'CA',
    translateCode: 'FR',
    code: 'FR',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'Portuguese (BR)',
    localDialect: 'Português',
    countryName: 'Brazil',
    countryCode: 'BR',
    code: 'PT-BR',
    translateCode: 'PT-BR',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'German',
    localDialect: 'Deutsch',
    countryName: 'Germany',
    countryCode: 'DE',
    code: 'DE',
    translateCode: 'DE',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'English (UK)',
    localDialect: 'English',
    countryName: 'United Kingdom',
    countryCode: 'GB',
    code: 'EN-GB',
    translateCode: 'EN-GB',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'Italian',
    localDialect: 'Italiano',
    countryName: 'Italy',
    countryCode: 'IT',
    code: 'IT',
    translateCode: 'IT',
    transcription: true,
    translation: true,
    dubbing: true,
  },
  {
    languageName: 'Chinese (Mandarin)',
    localDialect: '中文 (Zhōngwén)',
    countryName: 'China',
    countryCode: 'CN',
    code: 'ZH',
    translateCode: 'ZH',
    transcription: true,
    translation: true,
    dubbing: false,
  },
  {
    languageName: 'Hindi',
    localDialect: 'हिन्दी (Hindī)',
    countryName: 'India',
    countryCode: 'IN',
    transcription: true,
    translation: false,
    dubbing: true,
  },
  {
    languageName: 'Russian',
    localDialect: 'Русский (Russkiy)',
    countryName: 'Russia',
    countryCode: 'RU',
    code: 'RU',
    translateCode: 'RU',
    transcription: true,
    translation: true,
    dubbing: false,
  },
  {
    languageName: 'Arabic',
    localDialect: 'العربية (Al - ʿarabiyyah)',
    countryName: 'Saudi Arabia',
    countryCode: 'SA',
    transcription: true,
    translateCode: 'AR',
    translation: true,
    dubbing: false,
  },
  {
    languageName: 'Korean',
    localDialect: 'العربية (Al - ʿarabiyyah)',
    countryName: 'South Korea',
    countryCode: 'KR',
    code: 'KO',
    translateCode: 'KO',
    transcription: true,
    translation: true,
    dubbing: false,
  },
  {
    languageName: 'Japanese',
    localDialect: '日本語 (Nihongo)',
    countryName: 'Japan',
    countryCode: 'JP',
    code: 'JA',
    translateCode: 'JA',
    transcription: true,
    translation: true,
    dubbing: false,
  },
  {
    languageName: 'Indonesian',
    localDialect: '日本語 (Nihongo)',
    countryName: 'Indonesian',
    countryCode: 'ID',
    code: 'ID',
    translateCode: 'ID',
    transcription: true,
    translation: true,
    dubbing: false,
  },
  {
    languageName: 'Bengali',
    localDialect: '日本語 (Nihongo)',
    countryName: 'India',
    countryCode: 'IN',
    transcription: false,
    translation: false,
    dubbing: false,
  },

  {
    languageName: 'Filipino',
    localDialect: '日本語 (Nihongo)',
    countryName: 'Philippines',
    countryCode: 'PH',
    transcription: false,
    translation: false,
    dubbing: false,
  },

  {
    languageName: 'Turkish',
    localDialect: 'Türkçe',
    countryName: 'Turkey',
    countryCode: 'TR',
    code: 'TR',
    translateCode: 'TR',
    transcription: true,
    translation: true,
    dubbing: false,
  },
];

export const TableHeader = [
  'Date',
  'Title',
  'Original Language',
  'Translated Language',
  'Preview Link',
];
