import Link from 'next/link';
import DashboardLayout from '../../components/dashboard/DashboardLayout';

const ManualJobs = () => {
  return (
    <div className="text-white">
      <h2 className="mb-s3 text-2xl">
        Manually handle tasks that do have been generated by the user
      </h2>
      <div>
        <Link
          href="/playground/social-media"
          className="my-s2 block hover:underline"
        >
          Go to Social Media Servicing
        </Link>
        <Link href="/playground/upload" className="my-s2 block hover:underline">
          Go to Upload
        </Link>
        <Link
          href="/playground/transcription"
          className="my-s2 block hover:underline"
        >
          Go to Transcriptions
        </Link>
        <Link
          href="/playground/translation"
          className="my-s2 block hover:underline"
        >
          Go to Translations
        </Link>

        <Link
          href="/playground/dubbing"
          className="my-s2 block hover:underline"
        >
          Go to Dubbing
        </Link>
        <Link
          href="/playground/audio-separation"
          className="my-s2 block hover:underline"
        >
          Go to Audio Separation
        </Link>
        <Link
          href="/playground/speaker-identification"
          className="my-s2 block hover:underline"
        >
          Go to Speaker Identification
        </Link>
      </div>
    </div>
  );
};

ManualJobs.getLayout = DashboardLayout;

export default ManualJobs;
